name: Libra Developers Website CI

on:
  push:
    branches: [ auto ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checks-out the Libra website repository under $GITHUB_WORKSPACE, so job can access it
    - uses: actions/checkout@v2
    # Installs node and yarn
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    # Install git
    - name: Install git
      run: |
        sudo apt --assume-yes update
        sudo apt --assume-yes install git
    # Test that building the site is successful
    - name: Build Site
      run: ./scripts/build_docs.sh -b
